apps/charada/urls.py
from django.urls import path
from apps.charada.views import *

app_name = 'charada'

urlpatterns = [
    path('home/', homeView.as_view(), name='home'),

    # JUGADAS
    path('listarJugadas', listarJugadasView.as_view(), name='listarJugadas'),
    path('deleteJugada/<int:pk>', deleteJugadaView.as_view(), name='deleteJugada'),

    # TIROS
    path('listarTiros', listarTirosView.as_view(), name='listarTiros'),
    path('crearTiros', crearTirosView.as_view(), name='crearTiros'),
    path('deleteTiro/<int:pk>', deleteTiroView.as_view(), name='deleteTiro'),

    # CONTABILIDAD
    path('listarContabilidad', listarContabilidadView.as_view(), name='listarContabilidad'),

    # CONFIGURACION
    path('cofiguracion', configuracionView.as_view(), name='cofiguracion'),
    path('tope', topeView.as_view(), name='tope'),

    #FECH
    path('enviandoJugadas', jugadasEnviadasView.as_view(), name='enviandoJugadas'),
    path('reporteGanacia', reporteGanaciaView.as_view(), name='reporteGanacia'),
    path('getLimitados', getLimitadosView.as_view(), name='getLimitados'),
    path('deleteLimitado/<str:pk>', deleteLimitadoView.as_view(), name='deleteLimitado'),
]

charada/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.utils import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.usuario.urls')),
    path('charada/', include('apps.charada.urls')),
    path('', include('pwa.urls')),
]

handler_400 = badRequest403
handler_403 = permissionDenied403
handler_404 = pageNotFound404
handler_500 = internalError500

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/charada/models.py
import datetime
from crum import get_current_user
from django.db import models
from django.db.models.signals import post_save
from django.forms import model_to_dict

from apps.usuario.models import Usuario

CHOICE_TIPO_JUGADA = (
    (1, 'Fijo'),
    (2, 'Corrido'),
    (3, 'Parlet'),
    (4, 'Centena')
)

CHOICE_HORARIO = (
    ('Tarde', 'Tarde'),
    ('Noche', 'Noche')
)

CHOICE_MODOS = (
    (1, 'Lista'),
    (2, 'Bote')
)

class Limitado(models.Model):
    numero = models.CharField(verbose_name='Numero limitado', max_length=7, blank=False, null=False)
    tipo = models.PositiveIntegerField(verbose_name='Para que tipo de jugada', blank=False, null=False, choices=CHOICE_TIPO_JUGADA)
    precio = models.PositiveIntegerField(verbose_name='Precio para el premio', blank=False, null=False)

    class Meta:
        db_table = 'Limitado'
        verbose_name = 'Limitado'
        verbose_name_plural = 'Limitados'
        ordering = ['numero']

    def __str__(self):
        return 'Limitado: {0}, para {1}, precio a pagar {2}'.format(self.numero, self.getClaveTipo(), self.precio)

    def toJSON(self):
        item = model_to_dict(self)
        item['numero'] = self.numero
        item['tipo'] = self.tipo
        return item

    def getClaveTipo(self):
        if self.tipo == 1:
            return 'Fijo'
        if self.tipo == 2:
            return 'Corrido'
        if self.tipo == 3:
            return 'Parlet'

class Tiro(models.Model):
    primerNumero = models.PositiveIntegerField(verbose_name='Primer numero', blank=False, null=False)
    fijoCorrido = models.PositiveIntegerField(verbose_name='Primer numero fijo corrido', blank=False, null=False)
    primerCorrido = models.PositiveIntegerField(verbose_name='Primer numero corrido', blank=False, null=False)
    segundoCorrido = models.PositiveIntegerField(verbose_name='Segundo numero corrido', blank=False, null=False)
    fecha = models.DateField(verbose_name='Fecha del tiro', auto_now=True)
    horario = models.CharField(verbose_name='Horario del tiro', max_length=10, blank=False, null=False, choices=CHOICE_HORARIO)

    class Meta:
        db_table = 'Tiro'
        verbose_name = 'Tiro'
        verbose_name_plural = 'Tiros'

    def __str__(self):
        return 'Tiro de la {0}, del dia {1}'.format(self.horario, self.fecha)

    def getListaConLosTresNumerosCorridos(self):
        aux = []
        aux.append(self.fijoCorrido)
        aux.append(self.primerCorrido)
        aux.append(self.segundoCorrido)
        return aux

    def getCentena(self):
        centena = str(self.primerNumero)+str(self.fijoCorrido)
        return centena



class Jugada(models.Model):
    fk_usuario = models.ForeignKey(Usuario, verbose_name='Persona que entra la jugada', blank=False, null=False, on_delete=models.CASCADE)
    fk_tiro = models.ForeignKey(Tiro, verbose_name='Tiro', blank=True, null=True, on_delete=models.SET_NULL)
    numero = models.PositiveIntegerField(verbose_name='numero', blank=True, null=True)
    tipo = models.PositiveIntegerField(verbose_name='Tipo de jugada', blank=False, null=False, choices=CHOICE_TIPO_JUGADA)
    apostado = models.PositiveIntegerField(verbose_name='Apostado a la jugada', blank=False, null=False)
    premio = models.PositiveIntegerField(verbose_name='Premio', default=0, blank=True, null=True)
    fecha = models.DateTimeField(verbose_name='Fecha de entrada de las jugadas')
    parlet = models.CharField(max_length=5, blank=True, null=True)
    esGanadora = models.BooleanField(verbose_name='Jugada ganadora', default=False)

    class Meta:
        db_table = 'Jugada'
        verbose_name = 'Jugada'
        verbose_name_plural = 'Jugadas'

    def __str__(self):
        return '{0} pesos al {1} {2} dia {3}'.format(self.apostado, self.numero if self.tipo != 3 else self.parlet, self.getClaveTipo(), self.fecha)

    def getClaveTipo(self):
        if self.tipo == 1:
            return 'Fijo'
        if self.tipo == 2:
            return 'Corrido'
        if self.tipo == 3:
            return 'Parlet'
        if self.tipo == 4:
            return 'Centena'

class Configuracion(models.Model):
    modo = models.PositiveIntegerField(verbose_name='Modo', blank=True, null=True, choices=CHOICE_MODOS)
    topeBola = models.PositiveIntegerField(verbose_name='Tope para Bola', blank=True, null=True)
    topeParlet = models.PositiveIntegerField(verbose_name='Tope para parlet', blank=True, null=False)
    topeCentena = models.PositiveIntegerField(verbose_name='Tope para centena', blank=True, null=True)

    class Meta:
        db_table = 'Configuracion'
        verbose_name = 'Configuracion'
        verbose_name_plural = 'Configuraciones'

    def __str__(self):
        return 'Configuracion: {0} {1} {2} {3}'.format(self.modo, self.topeBola, self.topeParlet, self.topeCentena)


class Logs(models.Model):
    fk_usuario = models.ForeignKey(Usuario, verbose_name='Persona que entra la jugada', related_name='jugada_usuario', blank=False, null=False, on_delete=models.CASCADE)
    descripcion = models.CharField(verbose_name='Descripcion', max_length=255, blank=True, null=True)
    fecha = models.DateField(verbose_name='Fecha de la jugada', auto_now=True)

    class Meta:
        db_table = 'Logs'
        verbose_name = 'Logs'
        verbose_name_plural = 'Logs'

    def __str__(self):
        return 'El usuario {0} realizo la siguiente accio: {1}, el dia {2}'.format(self.fk_usuario.username, self.descripcion, self.fecha)


class Contabilidad(models.Model):
    fk_tiro = models.ForeignKey(Tiro, verbose_name='Tiro', blank=True, null=True, on_delete=models.SET_NULL)
    fk_usuario = models.ForeignKey(Usuario, verbose_name='Usuario', blank=True, null=True, on_delete=models.CASCADE)
    bruto = models.PositiveIntegerField(verbose_name='Bruto', blank=False, null=False)
    limpio = models.PositiveIntegerField(verbose_name='Limpio', blank=False, null=False)
    premio = models.PositiveIntegerField(verbose_name='Premio', blank=False, null=False)
    fecha = models.DateTimeField(verbose_name='Fecha de entrada de las jugadas')

    class Meta:
        db_table = 'Contabilidad'
        verbose_name = 'Contabilidad'
        verbose_name_plural = 'Contabilidad'

    def __str__(self):
        return 'Contabilidad del dia {0} del listero {1}, Bruto:{2},  Limpio:{3}, Premio:{4} -- {5}'.format(self.fecha.date(), self.fk_usuario.username, self.bruto, self.limpio, self.premio, self.getHorario())

    def getSoloFecha(self):
        return self.fecha.date()

    def getHorario(self):
        if self.fecha.hour > 14:
            return "Tarde"
        else:
            return 'Noche'


def calcularPremio(sender, instance, **kwargs):
    listaLimitados, jugadasFijas, jugadasCorridas, jugadasParlet, jugadasCentenas = [], [], [], [], []
    fecha = datetime.datetime.today()
    tiro = Tiro.objects.last()

    # FORMAR UNA LISTA CON LOS NUMEROS LIMITADOS
    limitados = Limitado.objects.all().values('numero')
    for i in limitados:
        listaLimitados.append(i['numero'])

    if tiro.horario == 'Tarde':
        print('jugadas de la tarde')
        #SEPARAR LAS JUGADAS POR TIPO
        try:
            jugadasTarde = Jugada.objects.filter(fecha__day=fecha.date().day, fecha__hour__lt=16)
            for i in jugadasTarde:
                i.fk_tiro = tiro
                i.save()
                if i.tipo == 1:
                    jugadasFijas.append(i)
                if i.tipo == 2:
                    jugadasCorridas.append(i)
                if i.tipo == 3:
                    jugadasParlet.append(i)
                if i.tipo == 4:
                    jugadasCentenas.append(i)
        except Exception as e:
            print(e)
            print('No se ha realizado el tiro de la tarde')

        for i in jugadasFijas:
            if i.numero == tiro.fijoCorrido and str(i.numero) in listaLimitados:
                objLimitado = Limitado.objects.get(numero=i.numero)
                if objLimitado.tipo == 1:
                    i.premio = i.apostado * objLimitado.precio
                    i.esGanadora = True
                    i.save()
                    print('fijo esta y es limitado')

            if i.numero == tiro.fijoCorrido and str(i.numero) not in listaLimitados:
                i.premio = i.apostado * 75
                i.esGanadora = True
                i.save()
                print('fijo esta y no es limitado')

        for i in jugadasCorridas:
            if i.numero in tiro.getListaConLosTresNumerosCorridos() and str(i.numero) in listaLimitados:
                objLimitado = Limitado.objects.get(numero=i.numero)
                if objLimitado.tipo == 2:
                    i.premio = i.apostado * objLimitado.precio
                    i.esGanadora = True
                    i.save()
                else:
                    i.premio = i.apostado * 25
                    i.esGanadora = True
                    i.save()
            if i.numero in tiro.getListaConLosTresNumerosCorridos() and str(i.numero) not in listaLimitados:
                i.premio = i.apostado * 25
                i.esGanadora = True
                i.save()

        for i in jugadasCentenas:
            if i.numero == int(tiro.getCentena()):
                i.premio = i.apostado * 400
                i.esGanadora = True
                i.save()
                print('centena esta')
            print('centena no esta')

        for i in jugadasParlet:
            primerNumero = int(i.parlet[0:2])
            segundoNumero = int(i.parlet[3:5])
            print(primerNumero, segundoNumero)
            if primerNumero in tiro.getListaConLosTresNumerosCorridos() and segundoNumero in tiro.getListaConLosTresNumerosCorridos() and i.parlet in listaLimitados:
                objLimitado = Limitado.objects.get(numero=i.parlet)
                i.premio = i.apostado * objLimitado.precio
                i.esGanadora = True
                i.save()

apps/charada/forms.py
from django.forms import *

from apps.charada.models import Limitado, Tiro


class limitadoForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Limitado
        fields = '__all__'
        widgets = {
            'numero': TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un numero', 'id': 'numeroLimitado'}),
            'tipo': Select(attrs={'class': 'form-control', 'placeholder': 'Seleccione una opcion', 'id': 'tipoLimitado'}),
            'precio': NumberInput(attrs={'class': 'form-control', 'readonly':True, 'id': 'precioLimitado'}),
        }

class tiroForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Tiro
        fields = '__all__'
        widgets = {
            'primerNumero': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un numero', 'id': 'primerNumero', 'required': True}),
            'fijoCorrido': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un numero', 'id': 'fijoCorrido', 'required': True}),
            'primerCorrido': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un numero', 'id': 'primerCorrido', 'required': True}),
            'segundoCorrido': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un numero', 'id': 'segundoCorrido', 'required': True}),
            'horario': Select(attrs={'class': 'form-control', 'placeholder': 'Seleccione una opcion', 'id': 'horario', 'required': True}),
        }

    def clean_primerNumero(self):
        data = str(self.cleaned_data['primerNumero'])
        if len(data) != 1:
            raise forms.ValidationError("La centena debe ser un numero de solo 1 digito.")
        return data

    def clean_fijoCorrido(self):
        data = str(self.cleaned_data['fijoCorrido'])
        if len(data) != 2:
            raise forms.ValidationError("El fijo debe ser un numero de solo 2 digitos.")
        return data

    def clean_primerCorrido(self):
        data = str(self.cleaned_data['primerCorrido'])
        if len(data) != 2:
            raise forms.ValidationError("Los corridos deben ser un numero de solo 2 digitos.")
        return data

    def clean_segundoCorrido(self):
        data = str(self.cleaned_data['segundoCorrido'])
        if len(data) != 2:
            raise forms.ValidationError("Los corridos deben ser un numero de solo 2 digitos.")
        return data

templates/charada/listar/contabilidad.html
{% extends 'comun/listar.html' %}
{% load static %}

{% block encabezadoTabla %}
    <i class="fa fa-table"></i> <strong>{{ titulo }}</strong>
{% endblock %}

{#{% block contentExtra %}#}
{#    <div class="row" id="reporteGanacia">#}
{#        <div class="col-sm-6">#}
{#            <h5 class="text-center"><strong>Reporte GAN/PER </strong>#}
{#            </h5>#}
{#            <div class="card" ref="formReporteGanPer">#}
{#                <div class="card-body">#}
{#                    <form class="forms-sample" name="formReporteGanPer" id="formReporteGanPer">#}
{#                        <div class="form-group row">#}
{#                            <label><span style="color: red">*</span><strong> Fecha Inicio</strong></label>#}
{#                            <div class="col-sm-9">#}
{#                                <input type="date" class="form-control" ref="fechaInicio" name="fechaInicio"#}
{#                                       placeholder="Ingrese un fecha">#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="form-group row">#}
{#                            <label><span style="color: red">*</span><strong> Fecha Fin</strong></label>#}
{#                            <div class="col-sm-9">#}
{#                                <input type="date" class="form-control" ref="fechaFin" name="fechaFin"#}
{#                                       placeholder="Ingrese una fecha">#}
{#                            </div>#}
{#                        </div>#}
{#                        <button type="button" class="btn btn-light mr-2" @click="salvarLimitado"#}
{#                                style=" box-shadow: 6px 7px 10px -5px rgba(0, 0, 0, 0.82);"><i#}
{#                                class="fa fa-save"></i> Salvar#}
{#                        </button>#}
{#                        <hr style="border-color: darkred;">#}
{#                        <div class="alert alert-secondary alert-dismissible fade show" ref="alertaReporte" hidden#}
{#                             role="alert"#}
{#                             style="box-shadow: 6px 7px 10px -4px rgba(0, 0, 0, 0.82);">#}
{#                            <div><strong>LIMPIO:</strong> ${$ limpio $}</div>#}
{#                            <hr>#}
{#                            <div><strong>PREMIO:</strong> ${$ premio $}</div>#}
{#                            <hr>#}
{#                            <div><strong>GAN/PER:</strong>#}
{#                                <span v-if="ganancia > 0" style="color: #1c7430"> ${$ganancia$}#}
{#                                    <i class="fa fa-arrow-up text-green"></i> (GANACIA)</span>#}
{#                                <span v-if="ganancia < 0" style="color: red">${$ganancia$}#}
{#                                    <i class="fa fa-arrow-down text-red   "></i> (PERDIDA)</span></div>#}
{#                            {% if 'usuario.administrador' in request.user.get_group_permissions %}#}
{#                                <hr>#}
{#                                <div><strong>%:</strong>#}
{#                                    <span style="color: #1c7430"> ${$porciento$}</span></div>#}
{#                            {% endif %}#}
{#                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                                <i class="ik ik-x"></i>#}
{#                            </button>#}
{#                        </div>#}
{#                    </form>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}


{% block table %}
    <table class="table table-hover table-striped table-bordered" id="tblCuadro">
        <thead>
        <tr>
            <th rowspan="">Acciones</th>
            <th rowspan="">Bruto</th>
            <th rowspan="">Limpio</th>
            <th rowspan="">Premio</th>
            <th rowspan="">Fecha</th>
            <th rowspan="">Hora</th>
        </tr>
        </thead>
        <tbody>
        {% for c in contabilidad %}
            <tr>
                <td>
                    <a class="Acciones eliminarTiro" href="#" data-id="{{ c.id }}"
                       type="button" title="Eliminar"><i class="fa fa-trash"></i></a>
                </td>
                <td class="text-center"><span class="badge badge-light">{{ c.bruto }}</span></td>
                <td class="text-center"><span class="badge badge-light">{{ c.limpio }}</span></td>
                <td class="text-center"><span class="badge badge-light">{{ c.premio }}</span></td>
                <td class="text-center"><span class="badge badge-light">{{ c.getSoloFecha }}</span></td>
                <td class="text-center"><span class="badge badge-light">{{ c.getSoloHora }}</span></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{#{% block extra_js %}#}
{#    <script>#}
{#        const messageError = (obj) => {#}
{#            var html = '';#}
{#            if (typeof (obj) === 'object') {#}
{#                html = '<ul style="text-align: left;">';#}
{#                $.each(obj, function (key, value) {#}
{#                    html += '<li>' + key + ': ' + value + '</li>';#}
{#                });#}
{#                html += '</ul>';#}
{#            } else {#}
{#                html = '<p>' + obj + '</p>';#}
{#            }#}
{#            toastr.error(html, 'Error', {#}
{#                progressBar: true,#}
{#                closeButton: true,#}
{#                "timeOut": "5000",#}
{#            });#}
{#        }#}
{##}
{#        const messageExito = (obj) => {#}
{#            var html = '';#}
{#            if (typeof (obj) === 'object') {#}
{#                html = '<ul style="text-align: left;">';#}
{#                $.each(obj, function (key, value) {#}
{#                    html += '<li>' + key + ': ' + value + '</li>';#}
{#                });#}
{#                html += '</ul>';#}
{#            } else {#}
{#                html = '<p>' + obj + '</p>';#}
{#            }#}
{#            toastr.success(html, 'Exito', {#}
{#                progressBar: true,#}
{#                closeButton: true,#}
{#                "timeOut": "3000",#}
{#            });#}
{#        };#}
{##}
{#        const reporteGanacia = new Vue({#}
{#            el: '#reporteGanacia',#}
{#            delimiters: ['{$', '$}'],#}
{#            data: {#}
{#                limpio: 0,#}
{#                premio: 0,#}
{#                ganancia: 0,#}
{#                porciento: 0#}
{##}
{#            },#}
{##}
{#            mounted() {#}
{#            },#}
{#            computed: {},#}
{#            methods: {#}
{##}
{##}
{#                salvarLimitado() {#}
{#                    let form = new FormData()#}
{#                    form.append('action', 'reporteGanPer')#}
{#                    form.append('fechaInicio', this.$refs.fechaInicio.value)#}
{#                    form.append('fechaFin', this.$refs.fechaFin.value)#}
{#                    console.log(form)#}
{#                    let dataRequest = {#}
{#                        method: 'POST',#}
{#                        body: form#}
{#                    }#}
{#                    const getJugadores = async () => {#}
{#                        try {#}
{#                            const response = await fetch('http://192.168.43.253:8080/charada/reporteGanacia', dataRequest)#}
{#                            const data = await response.json()#}
{#                            console.log(data)#}
{#                            if (!data.hasOwnProperty('error')) {#}
{#                                let alertaReporte = this.$refs.alertaReporte#}
{#                                alertaReporte.hidden = false#}
{#                                this.limpio = data.limpio#}
{#                                this.premio = data.premio#}
{#                                this.ganancia = data.ganancia#}
{#                                this.porciento = (this.limpio * 15) / 100#}
{#                                return false;#}
{#                            }#}
{#                            messageError(data.error);#}
{#                        } catch (error) {#}
{#                            console.log(error)#}
{#                        }#}
{#                    }#}
{#                    getJugadores()#}
{#                },#}
{#            },#}
{#        })#}
{#    </script>#}
{#{% endblock %}#}

templates/charada/listar/jugadas.html
{% extends 'comun/listar.html' %}
{% load static %}

{% block encabezadoTabla %}
    <i class="fa fa-table"></i> <strong>{{ titulo }}</strong>
{% endblock %}

{% block contentExtra %}
{% endblock %}


{% block table %}
    <table class="table table-hover table-striped table-bordered" id="tblCuadr">
        <thead>
        <tr>
            {% if 'usuario.administrador' in request.user.get_group_permissions %}
            <th rowspan="">Acciones</th>
            {% endif %}
            <th rowspan="">Entrada por</th>
            <th rowspan="">Tipo</th>
            <th rowspan="">Numero</th>
            <th rowspan="">Parlet</th>
            <th rowspan="">Apostado</th>
            <th rowspan="">es Ganadora</th>
            <th rowspan="">Premio</th>
            <th rowspan="">Fecha</th>
        </tr>
        </thead>
        <tbody>
        {% for jugada in jugadas %}
            <tr>
                {% if 'usuario.administrador' in request.user.get_group_permissions %}
                    <td>
                        <a class="eliminarJugada" href="#" data-id="{{ jugada.id }}"
                           type="button" title="Eliminar"><i class="fa fa-trash"></i></a>
                    </td>
                {% endif %}
                <td class="text-center"><span class="badge badge-light">{{ jugada.fk_usuario.username }}</span></td>
                <td class="text-center"><span class="badge badge-light">{{ jugada.get_tipo_display }}</span></td>
                {% if jugada.tipo == 3 %}
                    <td><a href="#" type="button"><i class="ml-40 fa fa-times-circle" style="color: red"></i></a></td>
                {% else %}
                    <td class="text-center"><span class="badge badge-light">{{ jugada.numero }}</span></td>
                {% endif %}
                {% if jugada.tipo == 1 or jugada.tipo == 2 or jugada.tipo == 4 %}
                    <td><a href="#" type="button"><i class="ml-40 fa fa-times-circle" style="color: red"></i></a></td>
                {% else %}
                    <td class="text-center"><span class="badge badge-light">{{ jugada.parlet }}</span></td>
                {% endif %}
                <td class="text-center"><span class="badge badge-light">{{ jugada.apostado }}</span></td>
                {% if jugada.esGanadora %}
                    <td><a href="#" type="button"><i class="fa fa-check-circle" style="color: #01ff70"></i></a></td>
                {% else %}
                    <td><a href="#" type="button" title="{{ clasificadorInd.activo }}"><i class="fa fa-times-circle"
                                                                                          style="color: red"></i></a>
                    </td>
                {% endif %}
                <td class="text-center"><span class="badge badge-light">{{ jugada.premio }}</span></td>
                <td class="text-center"><span class="badge badge-light">{{ jugada.fecha }}</span></td>


            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block js %}
    {{ block.super }}
    <script>
        $(document).on('click', '.eliminarJugada', function () {
            let idJugada = $(this).data('id');
            let url = 'http://127.0.0.1:8000/charada/deleteJugada/' + idJugada;
            fetch(url)
                .then(res => res.json())
                .then(data => {
                    console.log(data)
                    if (data.hasOwnProperty('error')) {
                        location.href = data.url
                        return false
                    }
                    location.href = data.url
                })
        });
    </script>
{% endblock %}