apps/charada/urls.py
from django.urls import path
from apps.charada.views import *

app_name = 'charada'

urlpatterns = [
    path('home/', homeView.as_view(), name='home'),

    # JUGADAS
    path('listarJugadas', listarJugadasView.as_view(), name='listarJugadas'),
    path('deleteJugada/<int:pk>', deleteJugadaView.as_view(), name='deleteJugada'),

    # TIROS
    path('listarTiros', listarTirosView.as_view(), name='listarTiros'),
    path('crearTiros', crearTirosView.as_view(), name='crearTiros'),
    path('deleteTiro/<int:pk>', deleteTiroView.as_view(), name='deleteTiro'),

    # CONTABILIDAD
    path('listarContabilidad', listarContabilidadView.as_view(), name='listarContabilidad'),

    # CONFIGURACION
    path('cofiguracion', configuracionView.as_view(), name='cofiguracion'),
    path('tope', topeView.as_view(), name='tope'),

    #FECH
    path('enviandoJugadas', jugadasEnviadasView.as_view(), name='enviandoJugadas'),
    path('reporteGanacia', reporteGanaciaView.as_view(), name='reporteGanacia'),
    path('getLimitados', getLimitadosView.as_view(), name='getLimitados'),
    path('deleteLimitado/<str:pk>', deleteLimitadoView.as_view(), name='deleteLimitado'),
]

apps/usuario/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from apps.usuario.views import *

app_name = 'usuario'

urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

charada/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.utils import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.usuario.urls')),
    path('charada/', include('apps.charada.urls')),
    path('', include('pwa.urls')),
]

handler_400 = badRequest403
handler_403 = permissionDenied403
handler_404 = pageNotFound404
handler_500 = internalError500

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/comun/base.html
{% load static %}
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>ABC | Project</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
        {#        <link rel="icon" href="../favicon.ico" type="image/x-icon"/>#}
        <link rel="stylesheet" href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/icon-kit/dist/css/iconkit.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}">
        <link rel="stylesheet"
              href="{% static 'plugins/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/theme/css/theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
        <link rel="stylesheet" href="{% static 'propios/css/styles.css' %}">
        <script src=" {% static 'plugins/vendor/modernizr-2.8.3.min.js' %}"></script>
    {% endblock %}

    {% block extra_css %}
    {% endblock %}
</head>

<body>
<div class="wrapper">
    <div class="page-wrap">
        <div class="main-content">
            <div class="container-fluid">
                {% block content %}
                    <div class="row">
                        <div class="col-lg-4 col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3>Resumen</h3>
                                    <div class="card-header-right">
                                        <ul class="list-unstyled card-option">
                                            <li><i class="ik ik-chevron-left action-toggle"></i></li>
                                            <li><i class="ik ik-minus minimize-card"></i></li>
                                            <li><i class="ik ik-x close-card"></i></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-block">
                                    <div class="row pp-main">
                                        <div class="col-xl-3 col-md-6">
                                            <div class="pp-cont">
                                                <div class="row align-items-center mb-20">
                                                    <div class="col-auto">
                                                        <i class="fas fa-cube f-24 text-mute"></i>
                                                    </div>
                                                    <div class="col text-right">
                                                        <h2 class="mb-0 text-blue">2476</h2>
                                                    </div>
                                                </div>
                                                <div class="row align-items-center mb-15">
                                                    <div class="col-auto">
                                                        <p class="mb-0">Total Pde productos</p>
                                                    </div>
                                                    <div class="col text-right">
                                                        <p class="mb-0 text-blue"><i
                                                                class="fas fa-long-arrow-alt-up mr-10"></i>64%</p>
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-blue" style="width:45%"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xl-3 col-md-6">
                                            <div class="pp-cont">
                                                <div class="row align-items-center mb-20">
                                                    <div class="col-auto">
                                                        <i class="fas fa-tag f-24 text-mute"></i>
                                                    </div>
                                                    <div class="col text-right">
                                                        <h2 class="mb-0 text-red">843</h2>
                                                    </div>
                                                </div>
                                                <div class="row align-items-center mb-15">
                                                    <div class="col-auto">
                                                        <p class="mb-0">Nuevas ordenes</p>
                                                    </div>
                                                    <div class="col text-right">
                                                        <p class="mb-0 text-red"><i
                                                                class="fas fa-long-arrow-alt-down mr-10"></i>34%</p>
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-red" style="width:75%"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xl-3 col-md-6">
                                            <div class="pp-cont">
                                                <div class="row align-items-center mb-20">
                                                    <div class="col-auto">
                                                        <i class="fas fa-random f-24 text-mute"></i>
                                                    </div>
                                                    <div class="col text-right">
                                                        <h2 class="mb-0 text-c-yellow">63%</h2>
                                                    </div>
                                                </div>
                                                <div class="row align-items-center mb-15">
                                                    <div class="col-auto">
                                                        <p class="mb-0">Rango de conversion</p>
                                                    </div>
                                                    <div class="col text-right">
                                                        <p class="mb-0 text-yellow"><i
                                                                class="fas fa-long-arrow-alt-up mr-10"></i>64%</p>
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-yellow" style="width:65%"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer chat-footer">
                                    <div class="input-wrap">
                                        <input type="text" readonly placeholder="Type and enter" class="form-control">
                                    </div>
                                    <a type="button" href="{% url 'usuario:login' %}" class="btn btn-icon btn-theme">
                                        <i class="fa fa-paper-plane" style="margin-top: 10px"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
        {% include 'comun/footer.html' %}
    </div>
</div>

{% block js %}
    <script src="{% static 'plugins/vendor/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'plugins/vue.js/vue.min.js' %}"></script>
    <script src="{% static 'plugins/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plugins/moment/moment.js' %}"></script>
    <script src="{% static 'plugins/tempusdominus-bootstrap-4/build/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
    <script src="{% static 'plugins/theme/js/theme.min.js' %}"></script>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'plugins/widgets.js' %}"></script>
{% endblock %}

{% block mensajes %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <script type="text/javascript">toastr.{{ message.tags }}('{{ message }}', 'Error', {
                    progressBar: true,
                    closeButton: true,
                    positionClass: "toast-bottom-left",
                    "timeOut": "3000",
                })</script>
            {% elif message.tags == 'info' %}
                <script type="text/javascript">toastr.{{ message.tags }}('{{ message }}', 'Información', {
                    progressBar: true,
                    closeButton: true,
                    positionClass: "toast-bottom-left",
                    "timeOut": "3000",
                })</script>
            {% else %}
                <script type="text/javascript">toastr.{{ message.tags }}('{{ message }}', 'Éxito', {
                    progressBar: true,
                    closeButton: true,
                    positionClass: "toast-bottom-left",
                    "timeOut": "3000",
                })</script>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}
</body>
</html>

templates/comun/crear.html
{% extends 'charada/home.html' %}
{% load static %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'plugins/bootstrapValidator/bootstrapValidator.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-4.0.13/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-4.0.13/css/select2-bootstrap4.min.css' %}">
     <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'propios/css/crear/styles.css' %}">
{% endblock %}

{% block content %}
    <div class="card" style="margin-top: 100px">
        <div class="card-header" >
            <h3>{% block encabezadoForm %}{% endblock %}</h3>
        </div>
        <div class="card-body">
            {% block formulario %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'plugins/bootstrapValidator/bootstrapValidator.min.js' %}"></script>
    <script src="{% static 'plugins/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'plugins/select2-4.0.13/js/i18n/es.js' %}"></script>
     <script src="{% static 'plugins/moment-2.25.3/moment-with-locales.js' %}"></script>
    <script src="{% static 'plugins/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js' %}"></script>
{% endblock %}

{% block grafico_js %}
{% endblock %}

templates/comun/footer.html
<footer class="footer">
    <div class="w-100 clearfix">
                    <span class="text-center text-sm-left d-md-inline-block">Copyright © 2022 Charada. Todos los
                        derechos reservados.</span>
        <span class="float-none float-sm-right mt-1 mt-sm-0 text-center">Creado <i
                class="fa fa-user text-danger"></i> por <a href="http://abcsoftware.app.netlify/"
                                                           class="text-dark"
                                                           target="_blank">abcsoftware</a></span>
    </div>
</footer>

templates/comun/header.html
{% load static %}
<header class="header-top" header-theme="light">
    <div class="container-fluid">
        <div class="d-flex justify-content-between">
            <div class="top-menu d-flex align-items-center">
                <button type="button" class="btn-icon mobile-nav-toggle d-lg-none"><span></span></button>
                <a type="button" href="{% url 'charada:home' %}" style="font-size: 25px; margin-left: 25px" class="btn-icon d-lg-none"><i class="fa fa-home"></i><span></span></a>
            </div>
            <div class="top-menu d-flex align-items-center">
                <div class="reloj" style="margin-right: 25px">
                    <i class="fas fa-clock mr-2"></i><span id="tiempo">00 : 00 : 00</span>
                </div>
                <span class="badge badge-light"> {{ request.user.username }}</span>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false"><img class="avatar"
                                                                       src="{% static 'propios/img/avatar5.png ' %}"
                                                                       alt=""></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{% url 'usuario:logout' %}"><i
                                class="ik ik-power dropdown-icon"></i>
                            Salir</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<script type="text/javascript">
    let html = document.getElementById("tiempo")

    setInterval(() => {
        tiempo = new Date

        horas = tiempo.getHours();
        minutos = tiempo.getMinutes();
        segundos = tiempo.getSeconds();

        if (horas < 10) {
            horas = "0" + horas;
        }
        if (minutos < 10) {
            minutos = "0" + minutos;
        }
        if (segundos < 10) {
            segundos = "0" + segundos;
        }
        html.innerHTML = horas + " : " + minutos + " : " + segundos;
        if (horas == 13 && minutos == 25 && segundos == 0) {
            toastr.warning('El sistema cerrara en 5 minutos.', 'Atencion', {
                progressBar: true,
                closeButton: true,
                "timeOut": "6000",
            });
        }
        if (horas == 13 && minutos == 30 && segundos == 0) {
                let url = 'http://127.0.0.1:8000/logout/'
                $.ajax({
                    url: url,
                }).done(function (response) {
                    window.location.reload()
                    console.log('aa')
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                })
            }
        if(horas == 21 && minutos == 25 && segundos == 0){
            toastr.warning('El sistema cerrara en 5 minutos.', 'Atencion', {
                progressBar: true,
                closeButton: true,
                "timeOut": "6000",
            });
        }
        if (horas == 21 && minutos == 30 && segundos == 0) {
                let url = 'http://127.0.0.1:8000/logout/'
                $.ajax({
                    url: url,
                }).done(function (response) {
                    window.location.reload()
                    console.log('aa')
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                })
            }
    }, 1000);
</script>

templates/comun/index.html
{% load static %}
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>ABC | Project</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
        {#        <link rel="icon" href="../favicon.ico" type="image/x-icon"/>#}
        <link rel="stylesheet" href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/icon-kit/dist/css/iconkit.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}">
        <link rel="stylesheet"
              href="{% static 'plugins/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/theme/css/theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
        <link rel="stylesheet" href="{% static 'propios/css/styles.css' %}">
        <script src=" {% static 'plugins/vendor/modernizr-2.8.3.min.js' %}"></script>
    {% endblock %}

    {% block extra_css %}
    {% endblock %}

    {% load pwa %}
    {% progressive_web_app_meta %}
</head>

<body>
<div class="wrapper">
    <div class="page-wrap">
        <div class="main-content">
            <div class="container-fluid">
                {% block content %}
                    <div class="row">
                        <div class="col-lg-4 col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3>Resumen</h3>
                                    <div class="card-header-right">
                                        <ul class="list-unstyled card-option">
                                            <li><a  href="{% url 'usuario:login' %}"><i class="ik ik-chevron-left action-toggle"></i></a></li>
                                            <li><i class="ik ik-minus minimize-card"></i></li>
                                            <li><i class="ik ik-x close-card"></i></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-block">
                                    <div class="row pp-main">
                                        <div class="col-xl-3 col-md-6">
                                            <div class="pp-cont">
                                                <div class="row align-items-center mb-20">
                                                    <div class="col-auto">
                                                        <i class="fas fa-cube f-24 text-mute"></i>
                                                    </div>
                                                    <div class="col text-right">
                                                        <h2 class="mb-0 text-blue">2476</h2>
                                                    </div>
                                                </div>
                                                <div class="row align-items-center mb-15">
                                                    <div class="col-auto">
                                                        <p class="mb-0">Total de productos</p>
                                                    </div>
                                                    <div class="col text-right">
                                                        <p class="mb-0 text-blue"><i
                                                                class="fas fa-long-arrow-alt-up mr-10"></i>64%</p>
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-blue" style="width:45%"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xl-3 col-md-6">
                                            <div class="pp-cont">
                                                <div class="row align-items-center mb-20">
                                                    <div class="col-auto">
                                                        <i class="fas fa-tag f-24 text-mute"></i>
                                                    </div>
                                                    <div class="col text-right">
                                                        <h2 class="mb-0 text-red">843</h2>
                                                    </div>
                                                </div>
                                                <div class="row align-items-center mb-15">
                                                    <div class="col-auto">
                                                        <p class="mb-0">Nuevas ordenes</p>
                                                    </div>
                                                    <div class="col text-right">
                                                        <p class="mb-0 text-red"><i
                                                                class="fas fa-long-arrow-alt-down mr-10"></i>34%</p>
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-red" style="width:75%"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xl-3 col-md-6">
                                            <div class="pp-cont">
                                                <div class="row align-items-center mb-20">
                                                    <div class="col-auto">
                                                        <i class="fas fa-random f-24 text-mute"></i>
                                                    </div>
                                                    <div class="col text-right">
                                                        <h2 class="mb-0 text-c-yellow">63%</h2>
                                                    </div>
                                                </div>
                                                <div class="row align-items-center mb-15">
                                                    <div class="col-auto">
                                                        <p class="mb-0">Rango de conversion</p>
                                                    </div>
                                                    <div class="col text-right">
                                                        <p class="mb-0 text-yellow"><i
                                                                class="fas fa-long-arrow-alt-up mr-10"></i>64%</p>
                                                    </div>
                                                </div>
                                                <div class="progress">
                                                    <div class="progress-bar bg-yellow" style="width:65%"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer chat-footer">
                                    <div class="input-wrap">
                                        <input type="text" readonly placeholder="Ingrese su correo" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
        {% include 'comun/footer.html' %}
    </div>
</div>

{% block js %}
    <script src="{% static 'plugins/vendor/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'plugins/vue.js/vue.min.js' %}"></script>
    <script src="{% static 'plugins/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plugins/moment/moment.js' %}"></script>
    <script src="{% static 'plugins/tempusdominus-bootstrap-4/build/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
    <script src="{% static 'plugins/theme/js/theme.min.js' %}"></script>
{% endblock %}

{% block extra_js %}
{% endblock %}

{% block mensajes %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <script type="text/javascript">toastr.{{ message.tags }}('{{ message }}', 'Error', {
                    progressBar: true,
                    closeButton: true,
                    positionClass: "toast-bottom-left",
                    "timeOut": "3000",
                })</script>
            {% elif message.tags == 'info' %}
                <script type="text/javascript">toastr.{{ message.tags }}('{{ message }}', 'Información', {
                    progressBar: true,
                    closeButton: true,
                    positionClass: "toast-bottom-left",
                    "timeOut": "3000",
                })</script>
            {% else %}
                <script type="text/javascript">toastr.{{ message.tags }}('{{ message }}', 'Éxito', {
                    progressBar: true,
                    closeButton: true,
                    positionClass: "toast-bottom-left",
                    "timeOut": "3000",
                })</script>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}
</body>
</html>

templates/comun/menu.html
{% load static %}
<div class="app-sidebar colored">
    <div class="sidebar-header">
        <a class="header-brand" href="{% url 'charada:home' %}">
            <div class="logo-img">
                <img src="{% static 'propios/img/favicon.png ' %}" class="header-brand-img" alt="lavalite">
            </div>
            <span class="text">Charada</span>
        </a>
        <button type="button" class="nav-toggle"><i data-toggle="expanded"
                                                    class="ik ik-toggle-right toggle-icon"></i></button>
        <button id="sidebarClose" class="nav-close"><i class="ik ik-x"></i></button>
    </div>

    <div class="sidebar-content">
        <div class="nav-container">
            <nav id="main-menu-navigation" class="navigation-main">
                <div class="nav-lavel">Menu</div>
                <div class="nav-item has-sub">
                    <a href="#"><i class="ik ik-box"></i><span>Charada</span></a>
                    <div class="submenu-content">
                        <a href="{% url 'charada:listarJugadas' %}" class="menu-item">Jugadas</a>
                        {% if 'usuario.banco' in request.user.get_group_permissions  or 'usuario.administrador' in request.user.get_group_permissions %}
                        <a href="{% url 'charada:listarContabilidad' %}" class="menu-item">Contabilidad</a>
                        {% endif %}
                        <a href="{% url 'charada:listarTiros' %}" class="menu-item">Tiros</a>

                    </div>
                </div>
                <div class="nav-item">
                    <a href="{% url 'charada:cofiguracion' %}"><i class="fa fa-cogs"></i><span>Configuración</span></a>
                </div>
            </nav>
        </div>
    </div>
</div>